---

vscode_repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
vscode_apt_key: "https://packages.microsoft.com/keys/microsoft.asc"

vscode_extensions:
  - 4ops.terraform
  - abusaidm.html-snippets
  - adrianwilczynski.add-reference
  - adrianwilczynski.asp-net-core-switcher
  - adrianwilczynski.blazor-snippet-pack
  - adrianwilczynski.csharp-to-typescript
  - adrianwilczynski.namespace
  - adrianwilczynski.terminal-commands
  - adrianwilczynski.toggle-hidden
  - adrianwilczynski.user-secrets
  - alireza94.theme-gotham
  - amazonwebservices.aws-toolkit-vscode
  - anseki.vscode-color
  - atlassian.atlascode
  - austenc.tailwind-docs
  - batisteo.vscode-django
  - bb-spectacle.bb-spectacle
  - bierner.markdown-mermaid
  - blanu.vscode-styled-jsx
  - boundarystudio.html-extentions-pack
  - bradlc.vscode-tailwindcss
  - ccimage.jsonviewer
  - christian-kohler.path-intellisense
  - codezombiech.gitignore
  - CoenraadS.bracket-pair-colorizer
  - cschlosser.doxdocgen
  - cssho.vscode-svgviewer
  - csstools.postcss
  - ctf0.php-namespace-resolver
  - docsmsft.docs-images
  - doggy8088.netcore-editorconfiggenerator
  - doggy8088.netcore-extension-pack
  - doggy8088.netcore-snippets
  - donjayamanne.githistory
  - donjayamanne.python-environment-manager
  - donjayamanne.python-extension-pack
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - emilast.LogFileHighlighter
  - Equinusocio.vsc-community-material-theme
  - Equinusocio.vsc-material-theme
  - equinusocio.vsc-material-theme-icons
  - esbenp.prettier-vscode
  - ex-codes.pine-script-syntax-highlighter
  - fernandoescolar.vscode-solution-explorer
  - formulahendry.code-runner
  - formulahendry.docker-explorer
  - formulahendry.docker-extension-pack
  - formulahendry.dotnet
  - formulahendry.dotnet-test-explorer
  - formulahendry.vscode-mysql
  - Fudge.auto-using
  - GitHub.copilot
  - GitHub.github-vscode-theme
  - GitHub.vscode-pull-request-github
  - GitLab.gitlab-workflow
  - golang.go
  - Gruntfuggly.todo-tree
  - hbenl.vscode-test-explorer
  - HookyQR.beautify
  - humao.rest-client
  - Insigne.powershell
  - jakebathman.mysql-syntax
  - jebbs.plantuml
  - jmrog.vscode-nuget-package-manager
  - jock.svg
  - johnpapa.winteriscoming
  - JonaDuran.my-light-theme
  - jorgeserrano.vscode-csharp-snippets
  - JuanBlanco.solidity
  - k--kato.docomment
  - kevin-chatham.aspnetcorerazor-html-css-class-completion
  - kreativ-software.csharpextensions
  - liximomo.sftp
  - magicstack.Chromodynamics
  - magicstack.MagicPython
  - mhutchie.git-graph
  - mkaufman.HTMLHint
  - mohsen1.prettify-json
  - mrmlnc.vscode-attrs-sorter
  - mrmlnc.vscode-doiuse
  - mrmlnc.vscode-scss
  - ms-azuretools.vscode-docker
  - MS-CEINTL.vscode-language-pack-es
  - ms-dotnettools.blazorwasm-companion
  - ms-dotnettools.csharp
  - ms-dotnettools.vscode-dotnet-runtime
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-mssql.data-workspace-vscode
  - ms-mssql.mssql
  - ms-mssql.sql-bindings-vscode
  - ms-mssql.sql-database-projects-vscode
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter-keymap
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode.cmake-tools
  - ms-vscode.cpptools
  - ms-vscode.cpptools-extension-pack
  - ms-vscode.cpptools-themes
  - ms-vscode.test-adapter-converter
  - ms-vsliveshare.vsliveshare
  - ms-vsliveshare.vsliveshare-audio
  - mtxr.sqltools
  - mtxr.sqltools-driver-mssql
  - mtxr.sqltools-driver-mysql
  - mtxr.sqltools-driver-pg
  - naumovs.color-highlight
  - Nimda.deepdark-material
  - njpwerner.autodocstring
  - Nur.just-black
  - octref.vetur
  - oderwat.indent-rainbow
  - oliversturm.fix-json
  - patcx.vscode-nuget-gallery
  - pflannery.vscode-versionlens
  - piotrpalarz.vscode-gitignore-generator
  - Pivotal.vscode-boot-dev-pack
  - Pivotal.vscode-concourse
  - Pivotal.vscode-spring-boot
  - PKief.material-icon-theme
  - redhat.fabric8-analytics
  - redhat.java
  - redhat.vscode-commons
  - redhat.vscode-microprofile
  - redhat.vscode-quarkus
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - ritwickdey.live-sass
  - ritwickdey.LiveServer
  - ScottSauber.blazorsnippets
  - sdras.night-owl
  - shardulm94.trailing-spaces
  - shd101wyy.markdown-preview-enhanced
  - sohibe.java-generate-setters-getters
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-spanish
  - thenikso.github-plus-theme
  - tht13.python
  - tintoy.msbuild-project-tools
  - tomaciazek.ansible
  - tomoki1207.pdf
  - twxs.cmake
  - vfd.vs2017-light-theme
  - vincaslt.highlight-matching-tag
  - VisualStudioExptTeam.vscodeintellicode
  - vscjava.vscode-java-debug
  - vscjava.vscode-java-dependency
  - vscjava.vscode-java-pack
  - vscjava.vscode-java-test
  - vscjava.vscode-maven
  - vscjava.vscode-spring-boot-dashboard
  - vscjava.vscode-spring-initializr
  - vscode-icons-team.vscode-icons
  - wayou.vscode-todo-highlight
  - william-voyek.vscode-nginx
  - yzane.markdown-pdf
  - yzhang.markdown-all-in-one
  - ZainChen.json
  - Zignd.html-css-class-completion
  - zxh404.vscode-proto3
...
